name: "Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
